export default [
  {
    name: "快的新出租小程序",
    time: "202012-至今",
    hide: true,
    role: "功能交付",
    isSeparate: true,
    duty: [
      "功能交付",
      "项目优化（体积、组件、组件库）",
      "推动进度",
      "营销增长",
    ],
    type: 3,
  },
  {
    name: "财务报销移动端",
    time: "202008-202010",
    role: "从0-->1",
    isSeparate: true,
    duty: [
      "react+mobx+less(module)",
      "所有页面开发",
      "发票费用智能审核",
      "表单组件封装，形成移动端开发表单交互标准",
    ],
    type: 2,
  },
  {
    name: "前端开发",
    time: "202007-202008",
    role: "优化过程",
    isSeparate: true,
    duty: ["优化考勤项目", "熟悉差旅项目", "熟悉和学习使用react相关技术栈"],
    type: 2,
  },
  {
    name: "前端规划",
    time: "202002-202006",
    role: "优化过程",
    isSeparate: true,
    duty: [
      "前端H5转发代理服务器维护",
      "开发脚手架，同意标准，支持初始化自定义，远程模板拉取等",
      "根据公司UED规范完成前端设计规范网站",
      "制订相关学习体系，并且自我学习",
    ],
    type: 1,
  },
  {
    name: "多级公文流转移动端V1.1.0",
    time: "201909-201911",
    role: "从0->1",
    isSeparate: true,
    duty: [
      "vue2+vue-cli3+vant项目构建和研发",
      "表单设计器的预览和交互兼容H5",
      "优化并制定相关的交互和动画标准",
    ],
    type: 1,
  },
  {
    name: "多级公文流转移动端V1.0.0",
    time: "201906-201909",
    role: "从0->1",
    isSeparate: true,
    duty: [
      "vue2+vue-cli3+vant项目构建和研发",
      "表单设计器的预览和交互兼容H5",
      "优化并制定相关的交互和动画标准",
    ],
    type: 1,
  },
  {
    name: "多级公文流转web端V1.0.0",
    time: "201903-201906",
    role: "从0->1",
    isSeparate: true,
    duty: [
      "vue2+vue-cli2+elementUI构建和研发",
      "公文流程设计器的单独生成",
      "公文表单设计器的单独生成",
      "使用canvas完成批注功能",
    ],
    type: 1,
  },
  {
    name: "内控系统V8.3.0+",
    time: "201901-201903",
    role: "从0->1",
    isSeparate: false,
    duty: [
      "很老的办公应用项目的更新修改，前后端未分离",
      "使用cdn的方式，vue+elementUI+jq的形式畸形研发",
      "为什么没有使用前后端分离？因为产品版本需求不一样，每次修改的页面是部分而非一次全部迭代",
    ],
    type: 1,
  },
  {
    name: "工作流系统移动端V2.0.0",
    time: "201811-201812",
    role: "从0->1",
    isSeparate: true,
    duty: [
      "移动端工作流系统，使用vue2+vue-cli+vux研发",
      "从0->1搭建",
      "使用nodeJS+webpack自动生成相关需要的补丁文件",
    ],
    type: 1,
  },
  {
    name: "工作流系统web端V8.3.0~V8.5.0",
    time: "201808-201811",
    role: "维护者",
    isSeparate: false,
    duty: [
      "很老的办公应用项目的更新修改，前后端未分离",
      "使用cdn的方式，vue+elementUI+jq的形式畸形研发",
    ],
    type: 1,
  },
  {
    name: "工作流引擎和表单设计器维护",
    time: "20180705-201808",
    role: "维护者",
    isSeparate: false,
    duty: [
      "基于开源项目bpmn-js经行修改的工作引擎，github地址：https://github.com/bpmn-io/bpmn-js",
      "流程设计器ui上面主要使用的jq",
      "使用preact（react的一个子类）书写的表单设计器插件，高度自定义，",
    ],
    type: 1,
  },
];
